server {
    listen 80;

    client_max_body_size 1G;

    # Requêtes vers /api/* → Symfony
    location /api {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Assets statiques de Symfony (bundles) → Symfony
    location /bundles {
        proxy_pass http://api:8000;
        proxy_set_header Host $host;
    }

    # Tout le reste → React
    location / {
        proxy_pass http://frontend:5173;
        proxy_set_header Host $host;

        # Nécessaire pour le hot reload de Vite (WebSocket)
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
